# Generated by Django 2.2.6 on 2019-10-14 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('middle_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=64, unique=True)),
                ('engine_number', models.CharField(max_length=64)),
                ('chassis_number', models.CharField(max_length=64)),
                ('vehicle_type', models.CharField(max_length=64)),
                ('number_of_cylinders', models.CharField(max_length=64)),
                ('gross_weight', models.CharField(max_length=64)),
                ('body_type', models.CharField(max_length=64)),
                ('fuel_type', models.CharField(max_length=64)),
                ('make', models.CharField(max_length=64)),
                ('model', models.CharField(max_length=64)),
                ('year', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('CLEARED', 'Cleared'), ('UNREGISTERED', 'Unregistered'), ('CARNAPPED', 'Carnapped'), ('DUPLICATE', 'Duplicate'), ('CODING', 'Coding Violation')], default='CLEARED', max_length=2)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.Vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('or_number', models.CharField(max_length=64, unique=True)),
                ('date', models.CharField(max_length=64)),
                ('registration_office', models.CharField(max_length=64)),
                ('certificate_number', models.CharField(max_length=64)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.Person')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.Vehicle')),
            ],
        ),
    ]
