# Generated by Django 2.2.6 on 2019-10-14 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclestatus',
            name='status',
            field=models.CharField(choices=[('CLEARED', 'Cleared'), ('UNREGISTERED', 'Unregistered'), ('CARNAPPED', 'Carnapped'), ('DUPLICATE', 'Duplicate'), ('CODING', 'Coding Violation')], default='CLEARED', max_length=64),
        ),
    ]
