# Generated by Django 2.2.6 on 2019-10-14 12:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0002_auto_20191014_0836'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_entry', models.DateTimeField(default=datetime.datetime(2019, 10, 14, 12, 2, 32, 222798))),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.Owner')),
                ('vehicleStatus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.VehicleStatus')),
            ],
        ),
    ]
