# Generated by Django 2.2.6 on 2019-10-14 13:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0004_auto_20191014_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleentry',
            name='time_entry',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 14, 13, 33, 6, 32793)),
        ),
    ]
