# Generated by Django 2.2.6 on 2019-10-14 15:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0006_auto_20191014_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='color',
            field=models.CharField(default='white', max_length=64),
        ),
        migrations.AlterField(
            model_name='vehicleentry',
            name='time_entry',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 14, 15, 49, 15, 91151)),
        ),
    ]
